server:
  port: 8080

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: orderflow
    password: orderflow
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: always
      continue-on-error: true

jwt:
  secret: mySecretKeyThatIsAtLeast32BytesLongForHS256Algorithm!
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
